name: Publish GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: |
          python -m pip install -e .
      - name: Generate docs site
        env:
          EDESKY_API_KEY: ${{ secrets.EDESKY_API_KEY }}
        run: |
          # automatic dashboard selection by name containing "Praha"; the script will auto-determine a reasonable
          # `--created-from` date based on the previously generated results, so we omit it here.
          python ./scripts/generate_docs.py --name-filter Praha --keywords cyklo
      # deploy the generated docs to gh-pages branch using a traditional action
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # use GITHUB_TOKEN to authenticate (default)
          # Can also set a custom PAT by providing a different secret
          publish_branch: gh-pages
